ARG BASE

FROM $BASE as build

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && \
  cat /etc/apk/repositories && \
  apk --no-cache --update add ca-certificates tzdata ffmpeg && \
  cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
  echo "Asia/Shanghai" >/etc/timezone && \
  apk del tzdata

ENTRYPOINT ["sleep", "infinity"] 
